#!/usr/bin/env bash
# First-run helper — reads a Neon pooled connection string on stdin (or from
# secrets.txt if present), derives the direct endpoint, generates the three
# required secrets, and writes a mode-600 .env file.
#
# Idempotent: if .env already exists, refuses to overwrite unless -f is passed.
#
# Usage:
#   ./scripts/setup-env.sh            # reads secrets.txt or prompts
#   ./scripts/setup-env.sh -f         # overwrite existing .env
#   echo "$NEON_URI" | ./scripts/setup-env.sh
#
# Neon's pooled endpoint hostname contains "-pooler"; the direct (unpooled)
# hostname is the same with "-pooler" stripped. Superset's metadata DB must
# use the direct endpoint (transaction pooling breaks prepared statements);
# dbt uses the pooled endpoint.

set -euo pipefail

FORCE=0
if [[ "${1:-}" == "-f" ]]; then FORCE=1; fi

cd "$(dirname "$0")/.."
ENV_FILE=".env"

if [[ -f "$ENV_FILE" && $FORCE -eq 0 ]]; then
  echo "ERROR: .env already exists. Pass -f to overwrite." >&2
  exit 1
fi

# Source the Neon pooled URI
POOLED=""
if [[ ! -t 0 ]]; then
  POOLED="$(cat)"
elif [[ -f "secrets.txt" ]]; then
  echo "Reading pooled URI from secrets.txt"
  POOLED="$(tr -d '\n\r' < secrets.txt)"
else
  echo "Paste the Neon POOLED connection string (from Neon dashboard → Connection Details → Pooled):"
  read -r POOLED
fi

POOLED="$(echo -n "$POOLED" | tr -d '\n\r' | xargs)"

if [[ -z "$POOLED" ]]; then
  echo "ERROR: empty Neon URI" >&2
  exit 1
fi

if [[ "$POOLED" != *"-pooler"* ]]; then
  echo "WARNING: hostname does not contain '-pooler' — is this really the pooled URI?" >&2
fi

DIRECT="${POOLED/-pooler/}"
SUPERSET_URI="postgresql+psycopg2${DIRECT#postgresql}"

SECRET_KEY="$(openssl rand -base64 42 | tr -d '\n')"
GUEST_JWT="$(openssl rand -base64 42 | tr -d '\n')"
ADMIN_PW="$(openssl rand -base64 24 | tr -d '\n' | tr '/+' '_-')"

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup-env.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# This file is gitignored. Do not commit.

SUPERSET_METADATA_DB_URI=${SUPERSET_URI}
ANALYTICS_DB_URI=${DIRECT}
NEON_POOLED_URI=${POOLED}

REDIS_URL=redis://redis:6379/0

SUPERSET_SECRET_KEY=${SECRET_KEY}
GUEST_TOKEN_JWT_SECRET=${GUEST_JWT}

ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PW}
ADMIN_EMAIL=imbilawork@gmail.com
ADMIN_FIRSTNAME=Craig
ADMIN_LASTNAME=Leppan

MAPBOX_API_KEY=
EOF

chmod 600 "$ENV_FILE"

echo
echo "wrote $ENV_FILE (mode 600)"
echo "admin login: admin / (see ADMIN_PASSWORD in .env)"
echo
echo "next:"
echo "  1. create schemas on Neon: paste sql/neon-init.sql into Neon SQL Editor"
echo "  2. docker compose up --build"
echo "  3. open http://localhost:8088"
